//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper1_Total_productionValue {
            get {
                return ((int)(this["Oper1_Total_productionValue"]));
            }
            set {
                this["Oper1_Total_productionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poly.")]
        public string Oper1_NameValue {
            get {
                return ((string)(this["Oper1_NameValue"]));
            }
            set {
                this["Oper1_NameValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EL")]
        public string Oper1_Mode_1Value {
            get {
                return ((string)(this["Oper1_Mode_1Value"]));
            }
            set {
                this["Oper1_Mode_1Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AB")]
        public string Oper1_Mode_2Value {
            get {
                return ((string)(this["Oper1_Mode_2Value"]));
            }
            set {
                this["Oper1_Mode_2Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper1_Mode_1_Total_productionValue {
            get {
                return ((int)(this["Oper1_Mode_1_Total_productionValue"]));
            }
            set {
                this["Oper1_Mode_1_Total_productionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper1_Mode_2_Total_productionValue {
            get {
                return ((int)(this["Oper1_Mode_2_Total_productionValue"]));
            }
            set {
                this["Oper1_Mode_2_Total_productionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Oper2_OnOffValue {
            get {
                return ((bool)(this["Oper2_OnOffValue"]));
            }
            set {
                this["Oper2_OnOffValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Oper1_OnOff_Mode2Value {
            get {
                return ((bool)(this["Oper1_OnOff_Mode2Value"]));
            }
            set {
                this["Oper1_OnOff_Mode2Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Oper2_OnOff_Mode1Value {
            get {
                return ((bool)(this["Oper2_OnOff_Mode1Value"]));
            }
            set {
                this["Oper2_OnOff_Mode1Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper2_Total_productionValue {
            get {
                return ((int)(this["Oper2_Total_productionValue"]));
            }
            set {
                this["Oper2_Total_productionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poly.")]
        public string Oper2_NameValue {
            get {
                return ((string)(this["Oper2_NameValue"]));
            }
            set {
                this["Oper2_NameValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FM")]
        public string Oper2_Mode_1Value {
            get {
                return ((string)(this["Oper2_Mode_1Value"]));
            }
            set {
                this["Oper2_Mode_1Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ETC")]
        public string Oper2_Mode_2Value {
            get {
                return ((string)(this["Oper2_Mode_2Value"]));
            }
            set {
                this["Oper2_Mode_2Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper2_Mode_1_Total_productionValue {
            get {
                return ((int)(this["Oper2_Mode_1_Total_productionValue"]));
            }
            set {
                this["Oper2_Mode_1_Total_productionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Oper2_Mode_2_Total_productionValue {
            get {
                return ((int)(this["Oper2_Mode_2_Total_productionValue"]));
            }
            set {
                this["Oper2_Mode_2_Total_productionValue"] = value;
            }
        }
    }
}
